SELECT
    row_to_json(t)
FROM (
    SELECT
        DATE_TRUNC('hour', "DT") AS "DT_HOUR",
        ROUND(AVG("TAAVG1M")::NUMERIC, 1) AS "AVG_TAAVG1M",
        ROUND(AVG("RHAVG1M")::NUMERIC, 0) AS "AVG_RHAVG1M",
        ROUND(AVG("DPAVG1M")::NUMERIC, 1) AS "AVG_DPAVG1M",
        ROUND(AVG("SRAVG1M")::NUMERIC, 0) AS "AVG_SRAVG1M",
        ROUND(AVG("SDUR1M")::NUMERIC, 0) AS "AVG_SDUR1M",
        ROUND(AVG("SRDSUM1D")::NUMERIC, 0) AS "AVG_SRDSUM1D",
        ROUND(AVG("TAMIN1D")::NUMERIC, 1) AS "AVG_TAMIN1D",
        ROUND(AVG("TAMAX1D")::NUMERIC, 1) AS "AVG_TAMAX1D",
        ROUND(AVG("RHMIN1D")::NUMERIC, 0) AS "AVG_RHMIN1D",
        ROUND(AVG("RHMAX1D")::NUMERIC, 0) AS "AVG_RHMAX1D",
        ROUND(AVG("TG1")::NUMERIC, 1) AS "AVG_TG1",
        ROUND(AVG("TG2")::NUMERIC, 1) AS "AVG_TG2",
        ROUND(AVG("TG3")::NUMERIC, 1) AS "AVG_TG3",
        ROUND(AVG("TG4")::NUMERIC, 1) AS "AVG_TG4",
        ROUND(AVG("TG5")::NUMERIC, 1) AS "AVG_TG5",
        ROUND(AVG("TG6")::NUMERIC, 1) AS "AVG_TG6",
        ROUND(AVG("TG7")::NUMERIC, 1) AS "AVG_TG7",
        ROUND(AVG("WD")::NUMERIC, 0) AS "AVG_WD",
        ROUND(AVG("WS")::NUMERIC, 1) AS "AVG_WS",
        ROUND(AVG("WDAVG2M")::NUMERIC, 0) AS "AVG_WDAVG2M",
        ROUND(AVG("WDMAX2M")::NUMERIC, 0) AS "AVG_WDMAX2M",
        ROUND(AVG("WDMIN2M")::NUMERIC, 0) AS "AVG_WDMIN2M",
        ROUND(AVG("WSAVG2M")::NUMERIC, 1) AS "AVG_WSAVG2M",
        ROUND(AVG("WSMAX2M")::NUMERIC, 1) AS "AVG_WSMAX2M",
        ROUND(AVG("WSMIN2M")::NUMERIC, 1) AS "AVG_WSMIN2M",
        ROUND(AVG("PAAVG1M")::NUMERIC, 1) AS "AVG_PAAVG1M"
    FROM
        meteo_data
    WHERE
        "DT" >= NOW() - INTERVAL '24 hours'
    GROUP BY
        "DT_HOUR"
    ORDER BY
        "DT_HOUR"
) t;