class Values:
    code_descriptions = {
        "ID": "Primary ID number",
        "S": "Weather station code",
        "RNAME": "Record name",
        "PW15M": "Present weather (WMO code table 4680)",
        "VIS": "Visibility",
        "TAAVG1M": "Air temperature (1 minute average)",
        "RHAVG1M": "Relative humidity (1 minute average)",
        "DPAVG1M": "Dew point temperature (1 minute average)",
        "PRSUM1H": "Precipitation accumulation (1 hour)",
        "SRAVG1M": "Global solar radiation (1 minute average)",
        "SDUR1M": "Sunshine duration (1 minute)",
        "SRDSUM1D": "Sunshine duration (1 day sum)",
        "TAMIN1D": "Air temperature (1 day minimum)",
        "TAMAX1D": "Air temperature (1 day maximum)",
        "RHMIN1D": "Relative humidity (1 day minimum)",
        "RHMAX1D": "Relative humidity (1 day maximum)",
        "TG1": "Air temperature 5 cm above ground",
        "TG2": "Air temperature at ground surface",
        "TG3": "Ground temperature 5 cm under surface",
        "TG4": "Ground temperature 10 cm under surface",
        "TG5": "Ground temperature 20 cm under surface",
        "TG6": "Ground temperature 50 cm under surface",
        "TG7": "Ground temperature 100 cm under surface",
        "WD": "Wind direction",
        "WS": "Wind speed",
        "WDAVG2M": "Wind direction (2 minutes average)",
        "WDMAX2M": "Wind direction (2 minutes maximum)",
        "WDMIN2M": "Wind direction (2 minutes minimum)",
        "WSAVG2M": "Wind speed (2 minutes average)",
        "WSMAX2M": "Wind speed (2 minutes maximum)",
        "WSMIN2M": "Wind speed (2 minutes minimum)",
        "PAAVG1M": "Atmospheric pressure (1 minute average)",
        "EXTDC": "External DC voltage",
        "STATUS": "Unit status",
        "DT": "Datetime"
    }

    code_units = {
        "ID": "",
        "S": "",
        "RNAME": "",
        "PW15M": "",
        "VIS": " m",
        "TAAVG1M": "°C",
        "RHAVG1M": "%",
        "DPAVG1M": "°C",
        "PRSUM1H": " mm",
        "SRAVG1M": " W/m²",
        "SDUR1M": " min",
        "SRDSUM1D": " min",
        "TAMIN1D": "°C",
        "TAMAX1D": "°C",
        "RHMIN1D": "%",
        "RHMAX1D": "%",
        "TG1": "°C",
        "TG2": "°C",
        "TG3": "°C",
        "TG4": "°C",
        "TG5": "°C",
        "TG6": "°C",
        "TG7": "°C",
        "WD": "°",
        "WS": " m/s",
        "WDAVG2M": "°",
        "WDMAX2M": "°",
        "WDMIN2M": "°",
        "WSAVG2M": " m/s",
        "WSMAX2M": " m/s",
        "WSMIN2M": " m/s",
        "PAAVG1M": " hPa",
        "EXTDC": " V",
        "STATUS": "",
        "DT": ""
    }