from sqlalchemy import Column, Integer, String, Float, TIMESTAMP
from database import Base

class MeteoDataModel(Base):
    __tablename__ = "meteo_data"

    ID = Column(Integer, primary_key = True, index = True)
    S = Column(String)
    RNAME = Column(String)
    PW15M = Column(String)
    VIS = Column(String)
    TAAVG1M = Column(Float)
    RHAVG1M = Column(Float)
    DPAVG1M = Column(Float)
    PRSUM1H = Column(Float)
    SRAVG1M = Column(Float)
    SDUR1M = Column(Float)
    SRDSUM1D = Column(Float)
    TAMIN1D = Column(Float)
    TAMAX1D = Column(Float)
    RHMIN1D = Column(Float)
    RHMAX1D = Column(Float)
    TG1 = Column(Float)
    TG2 = Column(Float)
    TG3 = Column(Float)
    TG4 = Column(Float)
    TG5 = Column(Float)
    TG6 = Column(Float)
    TG7 = Column(Float)
    WD = Column(Float)
    WS = Column(Float)
    WDAVG2M = Column(Float)
    WDMAX2M = Column(Float)
    WDMIN2M = Column(Float)
    WSAVG2M = Column(Float)
    WSMAX2M = Column(Float)
    WSMIN2M = Column(Float)
    PAAVG1M = Column(Float)
    EXTDC = Column(Float)
    STATUS = Column(Integer)
    DT = Column(TIMESTAMP)